# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_new_rails_app_development
  username: postgres

test:
  <<: *default
  database: my_new_rails_app_test

production:
  <<: *default
  database: my_new_rails_app_production
  username: my_new_rails_app
  password: <%= ENV["MY_NEW_RAILS_APP_DATABASE_PASSWORD"] %>
